### PR TITLE
fix(*): Work in progress to be compatible with TypeORM 0.3.1+

### PR DESCRIPTION
**Pull request by ArsenyYankovsky**
This is a work in progress PR making this driver compatible with TypeORM 0.3.1+.
Currently the tests are not working when driver is used against newer versions of TypeORM because of the new `save` method behavior as reported [here](https://github.com/typeorm/typeorm/issues/4293).

### CODE REVIEW

**Comment by ArsenyYankovsky** [comment]
Waiting on [this PR](https://github.com/typeorm/typeorm/pull/8825) to be merged, which fixes insert statements not returning generated values.

**Comment by calvin-summer** [comment]
hi! i'm curious whats the status on this? :eyes: I'm looking to switch to typeorm 0.3+ asap, but obviously want to wait for this compatibility pr to go in. I'd  also be open to reviewing or helping if you want.

**Comment by ArsenyYankovsky** [comment]
@calvin-summer I just released a version 2.4.0 of the driver that is compatible with TypeORM 0.3.5.

**Pull request merged**
